"""Add AnalyticsResult model

Revision ID: e8f4396575c3
Revises: 87f2f0f0a205
Create Date: 2026-07-06 19:45:03.688055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f4396575c3'
down_revision: Union[str, None] = '87f2f0f0a205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.Column('correlation_data', sa.JSON(), nullable=True),
    sa.Column('distribution_data', sa.JSON(), nullable=True),
    sa.Column('trend_data', sa.JSON(), nullable=True),
    sa.Column('outlier_data', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('executive_summary', sa.JSON(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_results_dataset_id'), 'analytics_results', ['dataset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_results_dataset_id'), table_name='analytics_results')
    op.drop_table('analytics_results')
    # ### end Alembic commands ###
